### ISSUE TITLE
Return meaningful error message on Validation failure

### ISSUE THREAD

**Issue by c650** [rambler-digital-solutions/actix-web-validator#20]
Current behaviour is that we just return BAD_REQUEST... However, this is not enough because then we don't know which field(s) failed validation.

Current code:
 https://github.com/rambler-digital-solutions/actix-web-validator/blob/master/src/error.rs#L51-L55 

If we change this method we can return a list of errors, or at least the first one

**Comment by Roms1383** [comment]
Well, I actually ran into the same issue but thought it was related to the way formatting is handled by [serde_json](https://github.com/serde-rs/json).

In case it can be useful, here's how I solved it :
https://github.com/serde-rs/json/issues/759#issuecomment-793461767

I realize it doesn't belong to serde_json and could be added to this crate documentation, what do you think @c650  ?

**Comment by Roms1383** [comment]
Haven't found a better way so far 😅  @c650

**Comment by c650** [comment]
@Roms1383 that is why i made my own fork of this for now

**Comment by quantumsheep** [comment]
Any update on this?

**Comment by singulared** [comment]
I will add some additional error information in 2.1
For JSON representation, you can use custom Config error_handler:
```rust
use actix_web::{web, App, HttpResponse, HttpServer, Responder, error};
use actix_web_validator::{QsQuery, QsQueryConfig, Error};
use serde::{Deserialize, Serialize};
use validator::Validate;

#[derive(Debug, Validate, Deserialize)]
pub struct Filter {
    #[validate(length(min = 3))]
    projects: Vec<i32>,
    #[validate(length(min = 2))]
    name: String,
}

async fn index(web::Path(path): web::Path<String>, query: QsQuery<Filter>) -> impl Responder {
    dbg!(query);
    HttpResponse::Ok().body(path)
}

#[derive(Serialize)]
pub struct ValidationErrorJsonPayload {
    pub message: String,
    pub fields: Vec<String>,
}

impl From<&validator::ValidationErrors> for ValidationErrorJsonPayload {
    fn from(error: &validator::ValidationErrors) -> Self {
        ValidationErrorJsonPayload {
            message: "Validation error".to_owned(),
            fields: error.field_errors().iter().map(|(field, _)| field.to_string()).collect(),
        }
    }
}

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(move || {
        App::new()
            .app_data(QsQueryConfig::default().error_handler(|err, _| {
                let json_error = match &err {
                    Error::Validate(error) => ValidationErrorJsonPayload::from(error),
                    _ => ValidationErrorJsonPayload { message: err.to_string(), fields: Vec::new() },
                };
                error::InternalError::from_response(err, HttpResponse::Conflict().json(json_error)).into()
            }))
            .service(web::resource("{path:.*}").route(web::get().to(index)))
    })
    .bind("127.0.0.1:8080")?
    .run()
    .await
}

```

**Comment by singulared** [comment]
Hi, @NexRX! If it's actual can you show MRE?

**Comment by NexRX** [comment]
> Hi, @NexRX! If it's actual can you show MRE?

I'm confused. Was this an accident?
I haven't worked with this crate for a while.

**Comment by nhnansari** [comment]
The code given in the comment is not correct and throws an error 
`  
    Error::Validate(error) => ValidationErrorJsonPayload::from(error),
   |                                               -------------------------------- ^^^^^ the trait 'std::convert::From<&validator::types::ValidationErrors>' is not implemented for 'ValidationErrorJsonPayload'
`
