### ISSUE TITLE
Update validator version

### ISSUE THREAD

**Issue by AzHicham** [rambler-digital-solutions/actix-web-validator#51]
Hello would it be possible to update validator version ?
I face some trait mismatch :/ 

Thank you

**Comment by DenuxPlays** [comment]
Same issue here

**Comment by DenuxPlays** [comment]
Stacktrace:
![image](https://github.com/rambler-digital-solutions/actix-web-validator/assets/83671398/1d366084-7e1b-41d2-a65b-4ccb9193b5c6)

Struct:
```rust
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Validate, ToSchema)]
pub struct BudgetDTO {
    #[validate(range(min = 0))]
    pub amount: i64,
    #[validate(length(min = 1, max = 255))]
    pub name: String,
    #[validate(length(min = 0, max = 255))]
    pub description: Option<String>,
    #[serde(with = "time::serde::rfc3339")]
    #[validate(custom(function = validate_datetime_not_in_future))]
    pub created_at: OffsetDateTime,
}
```
For a complete example look:
https://github.com/financrr/backend/tree/dependabot/cargo/validator-0.17.0
